package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Model
type Model struct {

	// CreatedAt
	CreatedAt strfmt.DateTime `json:"createdAt" xml:"createdAt"`
}
