package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// Validate validates this model
func (m *Model) Validate(formats strfmt.Registry) error {

	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}

	return nil
}

func (m *Model) validateCreatedAt(formats strfmt.Registry) error {

	// custom object strfmt.DateTime
	if err := m.CreatedAt.Validate(formats); err != nil {
		return err
	}

	return nil
}
